---
deployment:
  tasks:
    - export DEPLOYPATH=/home/daglorem/repositories/Daglore-Website
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R files $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp admission.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp gallery.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
